spring:
  application:
    name: spring
  data:
    web:
      pageable:
        one-indexed-parameters: true
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:33061/spring?serverTimezone=Asia/Seoul
    username: admin
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver